### ISSUE TITLE
Can't validate JSON Blobs.

### ISSUE THREAD

**Issue by rachel-rocks-at-ruby** [technicallyjosh/koa-fluent-validation#2]
:)

**Comment by technicallyjosh** [comment]
Hi there,

Can you be a bit more specific with providing examples or description of problems you are running into or what you are trying to accomplish with the lib?

**Comment by rachel-rocks-at-ruby** [comment]
Sure. I have request body that takes a JSON blob, so I want to validate a JSON blob was passed in. I think even validating it's an object would be sufficient. I'm not seeing a validator option for either. (Thanks for the great library, btw!)

**Comment by technicallyjosh** [comment]
Hey, thanks.

It does validate JSON blobs (objects) by default.

[See the wiki](https://github.com/technicallyjosh/koa-fluent-validation/wiki/Koa-Context-Functions-and-Properties#validatebodyvalidatorsetup-object-filtersetup-object)

99% of my use cases when writing this was JSON body validation.
